version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    container_name: laravel_app
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    container_name: laravel_web

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
